
target 'Project 4' do
use_frameworks!
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  pod 'GeoFire', :git => 'https://github.com/firebase/geofire-objc'
  pod 'INTULocationManager'

end
