    source 'https://github.com/CocoaPods/Specs.git'

target 'Project 4' do
use_frameworks!
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  pod 'Firebase/Messaging'
  pod 'GeoFire', :git => 'https://github.com/firebase/geofire-objc'
  pod 'INTULocationManager'
  pod 'GoogleMaps'
  pod 'GooglePlaces'
  pod 'GooglePlacePicker'

end
